### ISSUE TITLE
workspace aware

### ISSUE THREAD

**Issue by bradleyd** [codersauce/runst.nvim#1]
Thanks for putting this together. I have a project with multiple packages. To make it work, you need to pass `--pacakge` to cargo test.

```
cargo test --package utils it_starts_base_services_by_default
```

If I get some time, I can try to add this feature or wondering if you already have plans for it?

Thanks again.

**Comment by fcoury** [comment]
Thank you for taking the time to test and provide feedback.

I also work on such project and couldn't yet find the time to make that case work. After working on trying to write a clone of neovim in Rust[1], I learned a bit more about LSP and I may be able to use it to identify what are the runnable tests under the cursor.

I can't promise on a date, since things are very erratic at day job, but I would be interested in getting this to work as well.

If you wanted to take a shot at it yourself let me know and I might be able to point you on a direction.

--
[1] https://github.com/codersauce/red

**Comment by fcoury** [comment]
> Thanks for putting this together. I have a project with multiple packages. To make it work, you need to pass `--pacakge` to cargo test.

Hey there, just made it work with multiple packages. However it will need you to have lspconfig running and configured for rust-analyzer, otherwise it will fallback to the previous strategy.

Here's an example from my codebase:

```
Running: cargo test --package msuite --lib -- mcommons::utils::tests::test_ensure_dir --exact --show-output

running 1 test

test mcommons::utils::tests::test_ensure_dir ... ok

successes:

successes:
    mcommons::utils::tests::test_ensure_dir

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 498 filtered out; finished in 0.00s
```

Give it a try and let me know if it works for you.

**Comment by bradleyd** [comment]
You rock. Will give it a try today. Thanks

**Comment by bradleyd** [comment]
Works great. Tried it out on a few packages and so far catches all. If I get sometime this week, I will see if I can add run all at the top of the test run.

Thanks again for the quick response and turnaround.

**Comment by fcoury** [comment]
> Works great. Tried it out on a few packages and so far catches all. If I get sometime this week, I will see if I can add run all at the top of the test run.

That's awesome, glad to hwar!

> Thanks again for the quick response and turnaround.

You bet! Gonna close this issue now but be welcome to open another one if you find further issues.
